apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: simulator
  labels:
    app.kubernetes.io/name: simulator
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: simulator
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
